apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  namespace: monitor-prometheus
  annotations:
    kubernetes.io/ingress.global-static-ip-name: grafana-ip
    networking.gke.io/managed-certificates: grafana-cert
    
spec:
  defaultBackend:
    service:
      name: grafana
      port:
        number: 80
