apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: monitor-prometheus
spec:
  selector:
    app: app-site
  ports:
  - name: http
    port: 3000
    targetPort: 8080
  type: LoadBalancer