apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-site
  template:
    metadata:
      labels:
        app: app-site
    spec:
      containers:
      - name: app-container
        image: vmehta0387/vishal_test:latest
        ports:
        - containerPort: 8080