name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and push Docker image
        run: |
          docker build -t dummy-server .
          docker tag blockchecker:latest ${{ secrets.DOCKER_REPO_URL }}/blockchecker:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKER_REPO_URL }}/blockchecker:latest
      
